#!/usr/bin/env python3
"""Generate BOTH tokens.css and theme-dark.css from the unified theme-tokens.json.

Usage:
    python scripts/generate_theme_css.py            # write both CSS files
    python scripts/generate_theme_css.py --check    # CI mode: fail if stale

Source of truth: static/css/theme-tokens.json
Zero hardcoded color values in this script.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MAP_PATH = REPO_ROOT / "static" / "css" / "theme-tokens.json"
TOKENS_PATH = REPO_ROOT / "static" / "css" / "tokens.css"
DARK_PATH = REPO_ROOT / "static" / "css" / "theme-dark.css"


def _load() -> dict:
    return json.loads(MAP_PATH.read_text(encoding="utf-8"))


def _resolve_light(ref: str, data: dict) -> str:
    """Resolve a light-mode palette reference to var(--...) or literal."""
    if ref.startswith("ref:"):
        target = ref[4:]
        return f"var({target})"
    if ref.startswith("mint."):
        key = ref[5:]
        return f"var(--{key})"
    if ref.startswith("base."):
        key = ref[5:]
        return f"var(--{key})"
    return ref


def _resolve_dark(ref: str) -> str:
    """Resolve a dark-mode palette reference to var(--mt-palette-...)."""
    if ref.startswith("mt."):
        key = ref[3:]
        return f"var(--mt-palette-{key})"
    return ref


def generate_tokens(data: dict) -> str:
    """Generate the :root tokens.css (light defaults)."""
    palette = data["palette"]
    lines: list[str] = []

    lines.append("/*")
    lines.append(" * MINT Design Tokens + Semantic Layer")
    lines.append(" * ====================================")
    lines.append(" * AUTO-GENERATED by scripts/generate_theme_css.py from theme-tokens.json")
    lines.append(" * Do not edit by hand; update theme-tokens.json then re-run the generator.")
    lines.append(" *")
    lines.append(" * Checklist — new UI should use semantics (see docs/VISUAL_LAYER.md)")
    lines.append(" * Surfaces:     --background-default, --background-light, --app-background")
    lines.append(" * Text:         --text-default, --text-muted, --text-disabled, --text-critical")
    lines.append(" * Borders:      --border-default, --border-muted, --border-strong")
    lines.append(" * Actions:      --action-primary, --primary-interactive (+ hover/pressed)")
    lines.append(" * Chrome text:  --text-breadcrumb*, --text-page-subtitle")
    lines.append(" * Badges:       --badge-*-bg / --badge-*-text pairs defined below")
    lines.append(" */")
    lines.append("")
    lines.append(":root {")

    lines.append("  /* ── Mint Color Scales ─────────────────────────────── */")
    scale_groups = {
        "gray": [], "green": [], "blue": [], "red": [], "yellow": [],
        "orange": [], "violet": [], "purple": [], "cyan": [], "mist": [],
    }
    for key, val in palette["mint"].items():
        prefix = key.rsplit("-", 1)[0] if "-" in key else key
        if prefix in scale_groups:
            scale_groups[prefix].append((key, val))
        else:
            scale_groups.setdefault(prefix, []).append((key, val))

    for group_name, entries in scale_groups.items():
        if not entries:
            continue
        lines.append(f"\n  /* {group_name.capitalize()} */")
        for key, val in entries:
            lines.append(f"  --{key}: {val};")

    lines.append("\n  /* ── Alpha ────────────────────────────────────────── */")
    for token, pair in data["alpha"].items():
        light_val = pair["light"] if isinstance(pair, dict) else pair
        lines.append(f"  {token}: {light_val};")

    lines.append("\n  /* ── Base ─────────────────────────────────────────── */")
    for key, val in palette["base"].items():
        lines.append(f"  --{key}: {val};")

    lines.append("\n  /* ── Approved MT Palette ──────────────────────────── */")
    for key, val in palette["mt"].items():
        lines.append(f"  --mt-palette-{key}: {val};")

    lines.append("\n  /* ── Semantic Tokens (light) ─────────────────────── */")
    for token, pair in data["semantics"].items():
        light_ref = pair["light"]
        lines.append(f"  {token}: {_resolve_light(light_ref, data)};")

    lines.append("\n  /* ── Badge Pairs ─────────────────────────────────── */")
    for variant, pair in data["badges"].items():
        bg_light = pair["bg"]["light"]
        text_light = pair["text"]["light"]
        lines.append(f"  --badge-{variant}-bg: {_resolve_light(bg_light, data)};")
        lines.append(f"  --badge-{variant}-text: {_resolve_light(text_light, data)};")

    lines.append("\n  /* ── App Tokens ──────────────────────────────────── */")
    for token, pair in data["app_tokens"].items():
        light_ref = pair["light"]
        if light_ref.startswith("mint."):
            val = _resolve_light(light_ref, data)
        elif light_ref.startswith("ref:"):
            val = _resolve_light(light_ref, data)
        else:
            val = light_ref
        lines.append(f"  {token}: {val};")

    lines.append("\n  /* ── Bridges ─────────────────────────────────────── */")
    for token, pair in data["bridges"].items():
        light_ref = pair["light"]
        lines.append(f"  {token}: {_resolve_light(light_ref, data)};")

    lines.append("\n  /* ── Legacy Aliases ──────────────────────────────── */")
    for token, ref in data["legacy_aliases"].items():
        if token.startswith("_"):
            continue
        lines.append(f"  {token}: {_resolve_light(ref, data)};")

    lines.append("\n  /* ── Non-Color Tokens ────────────────────────────── */")
    for token, val in data["non_color"].items():
        resolved = _resolve_light(val, data) if val.startswith("ref:") else val
        lines.append(f"  {token}: {resolved};")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_dark(data: dict) -> str:
    """Generate theme-dark.css (dark overrides only)."""
    lines: list[str] = []

    lines.append("/*")
    lines.append(" * Dark theme — semantic + app token overrides.")
    lines.append(" * AUTO-GENERATED by scripts/generate_theme_css.py from theme-tokens.json")
    lines.append(" * Do not edit by hand; update theme-tokens.json then re-run the generator.")
    lines.append(" * Normative spec: docs/DARK_MODE_RESEARCH.md")
    lines.append(" */")
    lines.append("")
    lines.append('html[data-theme="dark"] {')

    lines.append("\n  /* ── Semantic tokens ─────────────────────────────── */")
    for token, pair in data["semantics"].items():
        dark_ref = pair.get("dark")
        if dark_ref is None:
            continue
        lines.append(f"  {token}: {_resolve_dark(dark_ref)};")

    lines.append("\n  /* ── Badge pairs ────────────────────────────────── */")
    for variant, pair in data["badges"].items():
        bg_dark = pair["bg"].get("dark")
        text_dark = pair["text"].get("dark")
        if bg_dark:
            lines.append(f"  --badge-{variant}-bg: {_resolve_dark(bg_dark)};")
        if text_dark:
            lines.append(f"  --badge-{variant}-text: {_resolve_dark(text_dark)};")

    lines.append("\n  /* ── Bridges ────────────────────────────────────── */")
    for token, pair in data["bridges"].items():
        dark_ref = pair.get("dark")
        if dark_ref is None:
            continue
        lines.append(f"  {token}: {_resolve_dark(dark_ref)};")

    lines.append("\n  /* ── App tokens ─────────────────────────────────── */")
    for token, pair in data["app_tokens"].items():
        dark_ref = pair.get("dark")
        if dark_ref is None:
            continue
        lines.append(f"  {token}: {_resolve_dark(dark_ref)};")

    lines.append("\n  /* ── Alpha / shadow overrides ────────────────────── */")
    for token, pair in data["alpha"].items():
        if isinstance(pair, dict) and pair.get("dark"):
            lines.append(f"  {token}: {pair['dark']};")

    lines.append("}")

    if "turbogrid" in data:
        lines.append("")
        lines.append("/* TurboGrid scoped dark overrides */")
        lines.append('html[data-theme="dark"] .turbogrid {')
        for token, pair in data["turbogrid"].items():
            dark_ref = pair.get("dark")
            if dark_ref is None:
                continue
            lines.append(f"  {token}: {_resolve_dark(dark_ref)};")
        if "turbogrid_alpha" in data:
            for token, value in data["turbogrid_alpha"].items():
                lines.append(f"  {token}: {value};")
        lines.append("}")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    check_mode = "--check" in sys.argv

    if not MAP_PATH.is_file():
        print(f"error: token map not found: {MAP_PATH}", file=sys.stderr)
        return 1

    data = _load()
    expected_tokens = generate_tokens(data)
    expected_dark = generate_dark(data)

    if check_mode:
        ok = True
        for path, expected, label in [
            (TOKENS_PATH, expected_tokens, "tokens.css"),
            (DARK_PATH, expected_dark, "theme-dark.css"),
        ]:
            if not path.is_file():
                print(f"error: {label} does not exist", file=sys.stderr)
                ok = False
                continue
            actual = path.read_text(encoding="utf-8")
            if actual != expected:
                print(
                    f"error: {label} is stale; re-run: python scripts/generate_theme_css.py",
                    file=sys.stderr,
                )
                ok = False
        if ok:
            print("ok: tokens.css and theme-dark.css match token map")
        return 0 if ok else 1

    TOKENS_PATH.write_text(expected_tokens, encoding="utf-8")
    DARK_PATH.write_text(expected_dark, encoding="utf-8")
    print(f"wrote {TOKENS_PATH.relative_to(REPO_ROOT)}")
    print(f"wrote {DARK_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
